AllCops:
  Include:
    - Gemfile
    - Rakefile

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Documentation:
  Enabled: false

FileName:
  Enabled: false

Next:
  Enabled: false
