sudo: false
language: ruby
rvm:
- 2.2.0
- 2.2.1
- 2.2.2
- 2.2.3
- 2.3.0
before_install: gem install bundler
script: bundle exec rake
bundler_args: "--without docs release repl"
env:
  global:
    secure: c+rp8AYFqcHxNFDZuq2BI5Ita65i/O97qgGYK/lNFj9d9bVRoWBRwlE4l1MBOTf4PpkeLWKcCc7sdzXP/k7QSpYi03hqGnERP0JMXEydumBblTuNbzvcuMNpvkVIvRy/UrebuMLh66tG6k42Mdg7vSxRypOAuCte/1Jjb0EvHHg=
